# Generated by Django 5.0 on 2023-12-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes_ecole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoles',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
