# Generated by Django 5.0 on 2024-01-01 23:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes_ecole', '0002_ecoles_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=155, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=255)),
                ('ville_residence', models.CharField(max_length=255)),
                ('piece_identite', models.ImageField(blank=True, upload_to='')),
                ('photo_profile', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Responsable Ecole',
                'verbose_name_plural': 'Responsable Ecoles',
            },
        ),
    ]
